{
  inputs = {
    chaotic = {
      url = "github:chaotic-cx/nyx/nyxpkgs-unstable";
    };
    home-manager = {
      follows = "chaotic/home-manager";
    };
    "icedos-github:icedos/apps" = {
      url = "github:icedos/apps/768b1fa7ece80cad011b33d74c692bd2c76540dc";
    };
    "icedos-github:icedos/apps-celluloid-celluloid-shader" = {
      flake = false;
      url = "path:///nix/store/5zcj323fgw0vxx0nhgvp45yxrwikm0c6-FSR.glsl";
    };
    "icedos-github:icedos/apps-flatpak-nix-flatpak" = {
      url = "github:gmodena/nix-flatpak/";
    };
    "icedos-github:icedos/desktop" = {
      url = "github:icedos/desktop/2eda900d2b2732d686825842a5cf64a0211e9217";
    };
    "icedos-github:icedos/gnome" = {
      url = "github:icedos/gnome/39f13b18573bec1ecdca5b27b172b64d87b5abc0";
    };
    "icedos-github:icedos/hardware" = {
      url = "github:icedos/hardware/3ed0f39dcefe9afb734e9d8ed9d9d8bd97f5de5d";
    };
    "icedos-github:icedos/providers" = {
      url = "github:icedos/providers/c8c06c007923371a6baedcabe55cb1b209f0f04b";
    };
    "icedos-github:icedos/tweaks" = {
      url = "github:icedos/tweaks/83d42744d78c418a259b8e1c4ae7eba1d3e9eaf5";
    };
    "icedos-github:icedos/users" = {
      url = "github:icedos/users/9ddc3663045cd05e7df3d99844b4b640741fe667";
    };
    nixpkgs = {
      follows = "chaotic/nixpkgs";
    };

  };

  outputs =
    {
      home-manager,
      nixpkgs,
      self,
      ...
    }@inputs:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      inherit (pkgs) lib;
      inherit (lib) fileContents flatten map;

      inherit (builtins) fromTOML;
      inherit ((fromTOML (fileContents ./config.toml))) icedos;

      icedosLib = import ./lib {
        inherit lib pkgs inputs;
        config = icedos;
        self = ./.;
      };

      inherit (icedosLib) modulesFromConfig;
    in
    {
      apps.${system}.init = {
        type = "app";
        program = toString (with pkgs; writeShellScript "icedos-flake-init" "exit");
      };

      nixosConfigurations."nixos" = nixpkgs.lib.nixosSystem rec {
        specialArgs = {
          inherit icedosLib inputs;
        };

        modules = [
          # Read configuration location
          (
            { lib, ... }:
            let
              inherit (lib) mkOption types;
            in
            {
              options.icedos.configurationLocation = mkOption {
                type = types.str;
                default = "/home/jim/NixBoss";
              };
            }
          )

          # Symlink configuration state on "/run/current-system/source"
          {
            # Source: https://github.com/NixOS/nixpkgs/blob/5e4fbfb6b3de1aa2872b76d49fafc942626e2add/nixos/modules/system/activation/top-level.nix#L191
            system.systemBuilderCommands = "ln -s ${self} $out/source";
          }

          # Internal modules and config
          (
            { lib, ... }:
            let
              inherit (lib) filterAttrs;

              getModules =
                path:
                map (dir: "/${path}/${dir}") (
                  let
                    inherit (lib) attrNames;
                  in
                  attrNames (filterAttrs (n: v: v == "directory") (builtins.readDir path))
                );
            in
            {
              imports = [ ./modules/options.nix ] ++ getModules ./.extra ++ getModules ./.private;
              config.system.stateVersion = "25.05";
            }
          )

          home-manager.nixosModules.home-manager

          { icedos.system.isFirstBuild = false; }

          (
            # Do not modify this file!  It was generated by ‘nixos-generate-config’
            # and may be overwritten by future invocations.  Please make changes
            # to /etc/nixos/configuration.nix instead.
            {
              config,
              lib,
              pkgs,
              modulesPath,
              ...
            }:

            {
              imports = [
                (modulesPath + "/installer/scan/not-detected.nix")
              ];

              boot.initrd.availableKernelModules = [
                "xhci_pci"
                "ahci"
                "nvme"
                "usbhid"
                "usb_storage"
                "sd_mod"
              ];
              boot.initrd.kernelModules = [ ];
              boot.kernelModules = [ "kvm-intel" ];
              boot.extraModulePackages = [ ];

              fileSystems."/" = {
                device = "/dev/disk/by-uuid/7762c723-93db-4a5b-8bea-3546ec37f3d4";
                fsType = "btrfs";
                options = [ "subvol=@" ];
              };

              fileSystems."/boot" = {
                device = "/dev/disk/by-uuid/D1A0-E882";
                fsType = "vfat";
                options = [
                  "fmask=0077"
                  "dmask=0077"
                ];
              };

              swapDevices = [ ];

              # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
              # (the default) this is the recommended approach. When using systemd-networkd it's
              # still possible to use this option, but it's recommended to use it in conjunction
              # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
              networking.useDHCP = lib.mkDefault true;
              # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
              # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

              nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
              hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            }
          )

        ]
        ++ modulesFromConfig.options
        ++ (modulesFromConfig.nixosModules { inherit inputs; });
      };
    };
}
